spring:
  datasource:
    url: jdbc:mysql://${LOCAL_DB_HOST:localhost}:3306/${LOCAL_DB_NAME:swp391-skincare-products-sales-system}
    username: ${LOCAL_DB_USERNAME:root}
    password: ${LOCAL_DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always  # Nếu cần load file `data.sql`