spring:
  datasource:
    url: jdbc:mysql://${AZURE_DB_HOST}:3306/${AZURE_DB_NAME}?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

open:
  api:
    title: API document
    version: v1.0.0
    description: API Service
    serverUrl: ${SWAGGER_SERVER_URL:https://swp391-skincare-products-sales-system.onrender.com/api/v1/swp391-skincare-products-sales-system}
    serverName: Server
    license: https://github.com/gahoccode215/SWP391_Skincare_Products_Sales_System